### ISSUE TITLE
Research workflow?

### ISSUE THREAD

**Issue by micahlt** [jaxcksn/NodeYak#2]
I'm interested in contributing to this project - I know you stated that you wouldn't reveal how you're accessing the auth and refresh token, but would you be willing to explain how you're documenting the requests?  Did you do a decompile of the app or are you intercepting network traffic?  Out of curiosity, I spun up an Android emulator and attempted to use mitmproxy to inspect the requests, but wasn't able to successfully.  From what I can tell, they've got the SSL cert pinned.

**Comment by alex634** [comment]
He isn't probably going to tell you because of his *morality arc* but I figured it out after playing around for a few hours. Basically, you need to run Android X86 in Virtual Box because of ease of rooting and modding Android X86. You can disable cert pinning there and intercept requests with mitmproxy. After installing Android X86 (Must be at least 9.0) in a virtual machine, you will need to install Magisk. Magisk can't install the normal route on X86, so you must mount and edit boot files on the drive from a Linux live CD. Here is a link to where you can get the files to install Magisk manually: https://github.com/HuskyDG/initrd-magisk/wiki. You can follow that guide. After that, you will need to make sure you install the Magisk App from the website or the Github page. After that, you will need to update Magisk using the Magisk app if it needs updating. You will need an Edxposed module to disable Cert pinning system wide. So you will need to install Edxposed and it's dependency (Riru). Edxposed has issues with the latest version of Riru so you must use 25.4.4 (https://github.com/RikkaApps/Riru/releases). With Edxposed, just use whatever the latest version is (https://github.com/ElderDrivers/EdXposed). Both Riru and Edxposed should be installed through Magisk. Once Edxposed is ready, install the Edxposed module to disable certificate checking (https://github.com/ViRb3/TrustMeAlready). Once you have done that, get Mitmproxy for your computer. Don't use the default package manager repositories. They are out of date and don't usually work. Just download directly from the main site (https://mitmproxy.org/). Once you have done that. Run the mitmweb binary to get a webview for mitmproxy and to start mitmproxy. After that, go into the wireless settings in the Android virtual machine and point it to the proxy port and the IP is generally 10.0.2.2 for the local computer, but I wouldn't count on that to always be true.

Mitmproxy will show the authorization keys in the post requests to api.yikyak.com/graphql.
I didn't grammar check this, just wanted to save others work that the repository owner refused to save others. No point in posting an API you can't even use.

**Comment by micahlt** [comment]
Appreciate your help on this!  Thank you!

**Comment by jaxcksn** [comment]
Issue answered.
